<a href="https://colab.research.google.com/github/vinayreddy100/TensorFlow/blob/master/Tenosrflow2_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow-gpu==2.0.0-alpha0

     |████████████████████████████████| 332.1MB 27kB/s 
     |████████████████████████████████| 419kB 46.0MB/s 
     |████████████████████████████████| 3.0MB 45.3MB/s 


In [0]:
import tensorflow as tf

In [2]:
tf.__version__

'2.2.0-rc3'

In [0]:
# define constant
tensor2 = tf.constant([[23, 4], [32, 51]])

In [9]:
tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [10]:
# shape of tensor
tensor2.shape

TensorShape([2, 2])

In [11]:
# get value sof constant
tensor2.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [0]:
# lets convert numpy to tensor
import numpy as np
numpy_tensor = np.array([[23, 4], [32, 51]])

In [15]:
numpy_tensor.shape

(2, 2)

In [0]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [17]:
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

In [18]:
# defining a variable
tf2_variable = tf.Variable([[1., 2., 3., 4.], [5., 6., 7., 8.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 4) dtype=float32, numpy=
array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float32)>

In [19]:
tf2_variable.shape

TensorShape([2, 4])

In [20]:
# get value sof variables
tf2_variable.numpy()

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float32)

In [24]:
# change specific value in variable
tf2_variable[0, 3].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 4) dtype=float32, numpy=
array([[  1.,   2., 100., 100.],
       [  5.,   6.,   7.,   8.]], dtype=float32)>

In [25]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 4) dtype=float32, numpy=
array([[  1.,   2., 100., 100.],
       [  5.,   6.,   7.,   8.]], dtype=float32)>

In [0]:
# operations with tensors
tensor = tf.constant([[1, 2], [2, 3]])


In [27]:
#addition between a scaler and tensor
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [4, 5]], dtype=int32)>

In [28]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3]], dtype=int32)>

In [29]:
# multiplication between tensor and scaler
tensor * 3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 6],
       [6, 9]], dtype=int32)>

In [30]:
# numpy functions on tensors
np.square(tensor)

array([[1, 4],
       [4, 9]], dtype=int32)

In [31]:
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.41421356, 1.73205081]])

In [32]:
# dot product between tensors
np.dot(tensor, tensor2)

array([[ 87, 106],
       [142, 161]], dtype=int32)

In [0]:
# strings in tensorflow
tf_string = tf.constant("Tensorflow")

In [36]:
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'Tensorflow'>

In [37]:
# simple operations
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [38]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114, 102, 108, 111, 119], dtype=int32)>

In [0]:
# storing arrays of strings
tf_string_array = tf.constant(['tensorflow', 'deep learning', 'machine learning'])

In [40]:
for i in tf_string_array:
  print(i)

tf.Tensor(b'tensorflow', shape=(), dtype=string)
tf.Tensor(b'deep learning', shape=(), dtype=string)
tf.Tensor(b'machine learning', shape=(), dtype=string)
